### ISSUE TITLE
When I add an `-c srt` option to convert subs to set, it gives me an exception:

### ISSUE THREAD

**Issue by fazibear** [nofxx/subtitle_it#9]
This commit: 64c6db59211f6a608f639676837875b0a02c373b brake things. Trying to parse original like srt. 
```
Choose (1-1): 1
Downloading 1 subtitle...
/Users/fazibear/dev/subtitle_it/lib/subtitle_it/subtime.rb:9:in `initialize': unhandled exception
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subline.rb:21:in `new'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subline.rb:21:in `block in filter'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subline.rb:20:in `map'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subline.rb:20:in `filter'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subline.rb:12:in `initialize'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/formats/srt.rb:25:in `new'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/formats/srt.rb:25:in `block in parse_srt'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/formats/srt.rb:19:in `each'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/formats/srt.rb:19:in `inject'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/formats/srt.rb:19:in `parse_srt'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subtitle.rb:73:in `parse_lines!'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subtitle.rb:69:in `parse_dump'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/subtitle.rb:39:in `initialize'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/bin.rb:43:in `new'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/bin.rb:43:in `down_a_sub'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/bin.rb:34:in `block in run!'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/bin.rb:33:in `each'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/bin.rb:33:in `run!'
	from /Users/fazibear/dev/subtitle_it/lib/subtitle_it/bin.rb:92:in `run!'
	from /Users/fazibear/dev/subtitle_it/bin/subtitle_it:66:in `<main>'
```

**Comment by fazibear** [comment]
This is fix: https://github.com/nofxx/subtitle_it/commit/64c6db59211f6a608f639676837875b0a02c373b#commitcomment-11231347

**Comment by fazibear** [comment]
did you fix it ?

**Comment by nofxx** [comment]
Going to, was trying to reencode bad ones. 
Incredible how windows devs make programs non utf-8.
It's like the mormons: They will never believe in anything that happened after 1995.

**Comment by fazibear** [comment]
Here is PR. This is small fix, is unusable without it.
